### ISSUE TITLE
The system can not find the path specified.

### ISSUE THREAD

**Issue by zedy-wj** [glaucia86/azure-sql-prisma-vue#15]
**Describe the issue:**
When executing the `azd provision` command, the path specified is wrong:
![image](https://user-images.githubusercontent.com/81678720/230874654-636d72b8-7cf4-43a8-b177-4e3005b2b899.png)

**Repro Steps:**

1. azd init -t <template_name>
2. azd package
3. azd provision

**Environment:**
OS: Windows
Azd version: azd version 0.8.0-beta.1-daily.2689578 (commit 3b28fc8f84717d732f646a3e3b9521204f122112)

**Expected behavior:**
Executing azd provision can pass.

@rajeshkamal5050, @glaucia86 for notification.

**Comment by glaucia86** [comment]
Hi, @zedy-wj.
This project is not supported yet to use azd. There's a PR here: https://github.com/glaucia86/azure-sql-prisma-vue/pull/12
that still in WIP.

Feel free to help us in this PR.
